import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: '#F5F7FA',
    flex: 1,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 12,
    color: '#1A237E',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#B0BEC5',
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    backgroundColor: '#fff',
    color: '#263238',
  },
  list: {
    marginBottom: 8,
    backgroundColor: '#fff',
    borderRadius: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#E3E6F0',
    paddingVertical: 8,
  },
  headerCell: {
    fontWeight: 'bold',
    color: '#1A237E',
    fontSize: 15,
    textAlign: 'left',
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  cell: {
    color: '#263238',
    fontSize: 15,
    textAlign: 'left',
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  cellType: {
    color: '#3949AB',
    fontSize: 15,
    textAlign: 'left',
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  actionIcon: {
    marginHorizontal: 4,
  },
  addButton: {
    backgroundColor: '#1976D2',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  addButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(26,35,126,0.7)',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 28,
    width: '95%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 22,
    marginBottom: 18,
    color: '#1A237E',
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 18,
  },
  editButton: {
    backgroundColor: '#1976D2',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginHorizontal: 4,
  },
  editButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  transactionButton: {
    backgroundColor: '#00897B',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginHorizontal: 4,
  },
  transactionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  iconButton: {
    padding: 8,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
  },
  saveButton: {
    backgroundColor: '#43A047',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginLeft: 8,
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: '#E53935',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    marginLeft: 8,
  },
  cancelButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderColor: '#B0BEC5',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#F5F7FA',
    color: '#263238',
    fontSize: 16,
    width: '100%',
  },
  picker: {
    marginBottom: 8,
    backgroundColor: '#F5F7FA',
    borderRadius: 6,
  },
  remarksInput: {
    borderWidth: 1,
    borderColor: '#B0BEC5',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
    backgroundColor: '#F5F7FA',
    color: '#263238',
  },
  formButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  formPicker: {
    marginBottom: 12,
    backgroundColor: '#F5F7FA',
    borderRadius: 8,
    borderColor: '#B0BEC5',
    borderWidth: 1,
  },
  customerFrequency: {
    color: '#00897B',
    fontSize: 15,
    textAlign: 'center',
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  sectionHeader: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#3949AB',
    marginTop: 18,
    marginBottom: 6,
  },
  formLabel: {
    fontWeight: '600',
    color: '#263238',
    marginBottom: 2,
    marginTop: 8,
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#B0BEC5',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#F5F7FA',
    color: '#263238',
    fontSize: 16,
    width: '100%',
  },
  formInputError: {
    borderWidth: 2,
    borderColor: '#FF3B30',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#FFF5F5',
    color: '#263238',
    fontSize: 16,
    width: '100%',
  },
  uploadButton: {
    backgroundColor: '#FFA000',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginHorizontal: 4,
    alignItems: 'center',
  },
  uploadButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  viewButton: {
    backgroundColor: '#0288D1',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginHorizontal: 4,
    alignItems: 'center',
  },
  viewButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  transactionEmpty: {
    textAlign: 'center',
    color: '#8E8E93',
    fontSize: 16,
    marginTop: 20,
  },
  documentLink: {
    color: '#007AFF',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  docModalCloseButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  docModalCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  statusButton: {
    backgroundColor: '#1976D2',
    borderRadius: 6,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginVertical: 5,
    alignItems: 'center',
  },
  statusButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export default styles; 